language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
script:
  - rm -rf _site
  - bundle exec jekyll build
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  on:
    branch: master
