markdown: kramdown
highlighter: pygments
rdiscount:
  extensions: [smart, autolink]

comments :
   provider: disqus
   disqus:
     short_name:  habedisblog

name: Hassan Abedi's blog
description: My personal homepage
url: http://habedi.github.com
